// Generated by CoffeeScript 2.3.2
(function() {
  var AVALABLE_LANGUAGE_CODE, CurrentLanguageCode, EL_BTN_HELP, EL_LABELUP, EL_SUB_TITLE, EL_TITLE, I18N_ENTRY, REVISION, URL_TO_TELEGRAM, URL_TO_TELEME_WEB, doFetch, err, fetchWithTimeout, getAvaliableLanguage, getI18nEntry, logLineUp, main, notifyFailure, openupTeleme, reinstateNodes;

  REVISION = 1;

  AVALABLE_LANGUAGE_CODE = {
    en: 'en',
    es: 'es', // Spanish
    hi: 'hi', // Hindi
    ar: 'ar', // Arabic
    pt: 'pt', // Portuguese
    //bn : 'bn' # Bengali language
    //pa : 'pa' # Punjabi
    de: 'de', // German
    fr: 'fr',
    ja: 'ja',
    ru: 'ru',
    ko: 'ko'
  };

  //zh : 'zh-hans'
  AVALABLE_LANGUAGE_CODE['zh-hans'] = 'zh-hans';

  AVALABLE_LANGUAGE_CODE['zh-hant'] = 'zh-hant';

  AVALABLE_LANGUAGE_CODE['zh-hk'] = 'zh-hant';

  AVALABLE_LANGUAGE_CODE['zh-tw'] = 'zh-hant';

  I18N_ENTRY = {
    en: {
      TITLE: 'Telegram Group Management Made Easy',
      SUB_TITLE: 'TeleMe delivers a robust solution for Telegram group management and analytics.',
      HELP_DESK: 'Help Desk',
      CONNECTING_TELEME: 'Connecting to TeleMe server...',
      CONNECTING_TELEGRAM: "Connecting to Telegram Web Service...",
      CONNECTING_TELEME_FAILED: 'Fail to connect to TeleMe server.',
      CONNECTING_TELEGRAM_FAILED: 'Fail to connect to Telegram Web Service.',
      CONNECTING_FAILED: 'Please check your network connection. \nError:',
      CONNECTING_RETRY: 'Retry connection?',
      LAUNCH: "Launch TeleMe."
    },
    es: {
      TITLE: 'La gestión del grupo Telegram es fácil',
      SUB_TITLE: "TeleMe ofrece una solución robusta para la gestión y análisis de grupos de Telegram.",
      HELP_DESK: "Help Desk",
      CONNECTING_TELEME: "Conexión al servidor TeleMe ...",
      CONNECTING_TELEGRAM: "Conexión al servicio web de Telegram ...",
      CONNECTING_TELEME_FAILED: "Fallo al conectar con el servidor TeleMe.",
      CONNECTING_TELEGRAM_FAILED: "No se puede conectar al servicio web de Telegram",
      CONNECTING_FAILED: "Verifique su conexión de red. \nError: ",
      CONNECTING_RETRY: "¿Reintentar la conexión?",
      LAUNCH: "Lanzamiento de TeleMe."
    },
    hi: {
      TITLE: 'Telegram समूह प्रबंधन ने आसान बना दिया',
      SUB_TITLE: 'टेलीमे Telegram समूह प्रबंधन और विश्लेषण के लिए एक मजबूत समाधान प्रदान करता है।',
      HELP_DESK: 'सहायता डेस्क',
      CONNECTING_TELEME: 'TeleMe सर्वर से कनेक्ट हो रहा है ...',
      CONNECTING_TELEGRAM: "टेलीग्राम वेब सेवा से कनेक्ट हो रहा है ...",
      CONNECTING_TELEME_FAILED: 'TeleMe सर्वर से कनेक्ट करने में विफल।',
      CONNECTING_TELEGRAM_FAILED: 'टेलीग्राम वेब सेवा से कनेक्ट करने में विफल।',
      CONNECTING_FAILED: 'कृपया अपना नेटवर्क कनेक्शन जांचें। \nत्रुटि: ',
      CONNECTING_RETRY: 'पुनः प्रयास करें?',
      LAUNCH: "टेलीमे लॉन्च करें।"
    },
    ar: {
      TITLE: "سهولة إدارة مجموعة Telegram",
      SUB_TITLE: 'تقدم TeleMe حلاً قويًا لإدارة مجموعة Telegram والتحليلات.',
      HELP_DESK: "مكتب المساعدة",
      CONNECTING_TELEME: "جارٍ الاتصال بخادم TeleMe ...",
      CONNECTING_TELEGRAM: "الاتصال بخدمة ويب Telegram ...",
      CONNECTING_TELEME_FAILED: "فشل الاتصال بخادم TeleMe.",
      CONNECTING_TELEGRAM_FAILED: "فشل الاتصال بخدمة ويب Telegram.",
      CONNECTING_FAILED: "الرجاء التحقق من اتصالك بالشبكة. \ n الخطأ: ",
      CONNECTING_RETRY: "إعادة محاولة الاتصال؟",
      LAUNCH: "إطلاق TeleMe."
    },
    pt: {
      TITLE: 'Gerenciamento do grupo Telegram facilitado',
      SUB_TITLE: 'O TeleMe oferece uma solução robusta para gerenciamento e análise de grupos Telegram.',
      HELP_DESK: 'help desk',
      CONNECTING_TELEME: 'Conectando ao servidor TeleMe ...',
      CONNECTING_TELEGRAM: "Conectando ao Telegram Web Service ...",
      CONNECTING_TELEME_FAILED: 'Falha ao conectar-se ao servidor TeleMe.',
      CONNECTING_TELEGRAM_FAILED: 'Falha ao conectar ao Telegram Web Service.',
      CONNECTING_FAILED: 'Por favor, verifique sua conexão de rede. \ nErro: ',
      CONNECTING_RETRY: 'Repetir conexão?',
      LAUNCH: "Inicie o TeleMe."
    },
    //bn :
    //TITLE : ''
    //SUB_TITLE : ''
    //HELP_DESK : ''
    //CONNECTING_TELEME : ''
    //CONNECTING_TELEGRAM : ''
    //CONNECTING_TELEGRAM_FAILED : ''
    //CONNECTING_TELEGRAM_FAILED  : ''
    //CONNECTING_FAILED : ''

    //pa :
    //TITLE : ''
    //SUB_TITLE : ''
    //HELP_DESK : ''
    //CONNECTING_TELEME : ''
    //CONNECTING_TELEGRAM : ''
    //CONNECTING_TELEGRAM_FAILED : ''
    //CONNECTING_TELEGRAM_FAILED  : ''
    //CONNECTING_FAILED : ''
    de: {
      TITLE: 'Telegram-Gruppenverwaltung leicht gemacht',
      SUB_TITLE: 'TeleMe bietet eine robuste Lösung für das Management und die Analyse von Telegram-Gruppen.',
      HELP_DESK: 'Helpdesk',
      CONNECTING_TELEME: 'Verbindung zum TeleMe-Server ...',
      CONNECTING_TELEGRAM: "Verbindung zum Telegramm-Webdienst herstellen ...",
      CONNECTING_TELEME_FAILED: 'Verbindung zum TeleMe-Server kann nicht hergestellt werden.',
      CONNECTING_TELEGRAM_FAILED: 'Verbindung zum Telegrammwebdienst kann nicht hergestellt werden.',
      CONNECTING_FAILED: 'Bitte überprüfen Sie Ihre Netzwerkverbindung. \nFehler: ',
      CONNECTING_RETRY: 'Verbindung erneut versuchen?',
      LAUNCH: "TeleMe starten."
    },
    fr: {
      TITLE: 'La gestion de groupe Telegram simplifiée',
      SUB_TITLE: "TeleMe fournit une solution robuste pour la gestion et l'analyse de groupe Telegram.",
      HELP_DESK: 'help desk',
      CONNECTING_TELEME: 'Connexion au serveur TeleMe ...',
      CONNECTING_TELEGRAM: "Connexion au service Web Telegram ...",
      CONNECTING_TELEME_FAILED: 'Echec de la connexion au serveur TeleMe.',
      CONNECTING_TELEGRAM_FAILED: 'Echec de la connexion au service Web Telegram.',
      CONNECTING_FAILED: 'Veuillez vérifier votre connexion réseau. \nError: ',
      CONNECTING_RETRY: 'Réessayer la connexion?',
      LAUNCH: "Lancez TeleMe."
    },
    ja: {
      TITLE: "Telegram コミュニティの操作は便利です",
      SUB_TITLE: "TeleMeはあなたに強力なコミュニティ管理ツールを提供します。 ",
      HELP_DESK: "ヘルプをリクエストする",
      CONNECTING_TELEME: "TeleMeサーバーに接続しています...",
      CONNECTING_TELEGRAM: "テレグラムプラットフォームに接続しています...",
      CONNECTING_TELEME_FAILED: "TeleMeサーバーに接続できません！ ",
      CONNECTING_TELEGRAM_FAILED: "テレグラムプラットフォームに接続できません！ ",
      CONNECTING_FAILED: "ネットワーク設定を確認して、もう一度お試しください。 \ nエラーメッセージ ",
      CONNECTING_RETRY: "接続を再試行しますか？ ",
      LAUNCH: "TeleMeを起動してください。"
    },
    ru: {
      TITLE: "Групповое управление Telegram упростилось",
      SUB_TITLE: "TeleMe обеспечивает надежное решение для управления и анализа групп Telegram.",
      HELP_DESK: "справочная служба",
      CONNECTING_TELEME: "Подключение к серверу TeleMe ...",
      CONNECTING_TELEGRAM: "Подключение к веб-службе Telegram ...",
      CONNECTING_TELEME_FAILED: "Не удалось подключиться к серверу TeleMe.",
      CONNECTING_TELEGRAM_FAILED: "Не удалось подключиться к веб-сервису Telegram.",
      CONNECTING_FAILED: "Проверьте подключение к сети. \nНомер ошибки:",
      CONNECTING_RETRY: "Повторить соединение?",
      LAUNCH: "Запустить TeleMe."
    },
    ko: {
      TITLE: 'Telegram 전신 커뮤니티가 편리하게 운영됩니다',
      SUB_TITLE: 'TeleMe는 강력한 커뮤니티 관리 도구를 제공합니다. ',
      HELP_DESK: '고객 서비스에 문의하십시오',
      CONNECTING_TELEME: 'TeleMe 서버 연결 중 ...',
      CONNECTING_TELEGRAM: '텔레 그램 플랫폼 연결 중 ...',
      CONNECTING_TELEME_FAILED: 'TeleMe 서버에 연결할 수 없습니다! ',
      CONNECTING_TELEGRAM_FAILED: '전보 플랫폼에 연결할 수 없습니다! ',
      CONNECTING_FAILED: '네트워크 설정을 확인하고 다시 시도하십시오. \n오류 메시지 ',
      CONNECTING_RETRY: '연결을 다시 시도 하시겠습니까? ',
      LAUNCH: "TeleMe를 시작하십시오."
    },
    "zh-hans": {
      TITLE: 'Telegram电报社群运营得心应手',
      SUB_TITLE: 'TeleMe为您提供功能强大的社群管理工具。',
      HELP_DESK: '联系客服',
      CONNECTING_TELEME: '正在连接TeleMe服务器...',
      CONNECTING_TELEGRAM: '正在连接Telegram平台...',
      CONNECTING_TELEME_FAILED: '无法连接到TeleMe服务器！',
      CONNECTING_TELEGRAM_FAILED: '无法连接到Telegram平台！',
      CONNECTING_FAILED: '请检查您的网络设置，然后再重试。 \n错误信息',
      CONNECTING_RETRY: '要重试连接吗？',
      LAUNCH: "启动TeleMe."
    },
    "zh-hant": {
      TITLE: 'Telegram電報社群運營得心應手',
      SUB_TITLE: 'TeleMe為您提供功能強大的社群管理工具。',
      HELP_DESK: '聯繫客服',
      CONNECTING_TELEME: '正在連接TeleMe服務器...',
      CONNECTING_TELEGRAM: '正在連接Telegram平台...',
      CONNECTING_TELEME_FAILED: '無法連接到TeleMe服務器！ ',
      CONNECTING_TELEGRAM_FAILED: '無法連接到Telegram平台！ ',
      CONNECTING_FAILED: '請檢查您的網絡設置，然後再重試。 \n錯誤信息',
      CONNECTING_RETRY: '要重試連接嗎？ ',
      LAUNCH: '啟動TeleMe.'
    }
  };

  EL_TITLE = null;

  EL_SUB_TITLE = null;

  EL_LABELUP = null;

  EL_BTN_HELP = null;

  getAvaliableLanguage = function(languageCode) {
    var first2Char, found;
    languageCode = String(languageCode || (navigator && navigator.language) || '').trim();
    if (languageCode.length < 2) {
      return 'en';
    }
    languageCode = languageCode.toLocaleLowerCase();
    first2Char = languageCode.substr(0, 2);
    found = AVALABLE_LANGUAGE_CODE[first2Char] || AVALABLE_LANGUAGE_CODE[languageCode.substr(0, 5)] || AVALABLE_LANGUAGE_CODE[languageCode.substr(0, 7)];
    found || (found = ((first2Char === 'zh') && "zh-hans") || 'en');
    return found;
  };

  CurrentLanguageCode = getAvaliableLanguage();

  //CurrentLanguageCode = getAvaliableLanguage('ru')
  getI18nEntry = function(entryId) {
    var set;
    if (!entryId) {
      return '';
    }
    set = I18N_ENTRY[CurrentLanguageCode] || I18N_ENTRY['en'];
    if (set[entryId]) {
      return set[entryId];
    }
    return I18N_ENTRY['en'][entryId] || entryId;
  };

  reinstateNodes = function(callback) {
    EL_TITLE = $('#ELTitle');
    EL_SUB_TITLE = $('#ELSubtitle');
    EL_LABELUP = $('#ELLabelUp');
    EL_BTN_HELP = $('#ELHelpDesk');
    EL_TITLE.text(getI18nEntry('TITLE'));
    EL_SUB_TITLE.text(getI18nEntry('SUB_TITLE'));
    $('#ELHelpDesk a').text(getI18nEntry('HELP_DESK'));
    EL_TITLE.fadeIn('slow', function() {
      EL_SUB_TITLE.fadeIn('slow', function() {
        EL_LABELUP.fadeIn('slow');
        callback();
      });
    });
  };

  URL_TO_TELEME_WEB = `https://www.teleme.io/desktop?rev=1&utm_source=teleme_desktop&utm_medium=referral&hl=${CurrentLanguageCode}&r=${Date.now()}`;

  console.log("URL_TO_TELEME_WEB:", URL_TO_TELEME_WEB);

  URL_TO_TELEGRAM = `https://telegram.org/js/telegram-widget.js?r=${Date.now()}`;

  console.log("URL_TO_TELEGRAM:", URL_TO_TELEGRAM);

  fetchWithTimeout = function(url) {
    return Promise.race([
      fetch(url),
      new Promise(function(_,
      reject) {
        return setTimeout((function() {
          return reject(new Error('Timeout'));
        }),
      8888);
      })
    ]);
  };

  doFetch = function(url, callback) {
    fetchWithTimeout(URL_TO_TELEME_WEB).then(function(res) {
      if (!(res && res.status >= 200 && res.status < 400)) {
        throw new Error(`invalid http status ${res.status} from the server.`);
      }
      return res;
    }).then(function() {
      return callback();
    }).catch(function(err) {
      console.log(`ERROR _httpGetJson url ${url}. error:`, err);
      callback(err);
    });
  };

  openupTeleme = function() {
    var options;
    options = {
      "title": "TeleMe Desktop",
      "width": 1118,
      "height": 888,
      "min_width": 518,
      "min_height": 518,
      "resizable": true,
      "frame": true
    };
    nw.Window.open(URL_TO_TELEME_WEB, options, function(newWin) {
      //newWin.on 'new-win-policy', (frame, url, policy)->

      //alert "url:#{url}"
      //return if url.indexOf("oauth.telegram") > 0

      //alert "url:#{url}, openExternal"
      //# do not open the window
      //policy.ignore()
      //# and open it in external browser
      //nw.Shell.openExternal(url)
      //return
      window.close(true);
    });
    analytics && analytics.event('client_desktop', 'go_web', {
      eventLabel: 'label'
    });
  };

  logLineUp = function(msg) {
    return EL_LABELUP.text(String(msg || ''));
  };

  main = function() {
    logLineUp(getI18nEntry("CONNECTING_TELEME"));
    doFetch(URL_TO_TELEME_WEB, function(err) {
      if (err != null) {
        logLineUp(getI18nEntry("CONNECTING_TELEME_FAILED"));
        notifyFailure(`${getI18nEntry("CONNECTING_TELEME_FAILED")}\n${getI18nEntry("CONNECTING_FAILED")}:${err}\n${getI18nEntry('CONNECTING_RETRY')}`);
        return;
      }
      logLineUp(getI18nEntry("CONNECTING_TELEGRAM"));
      doFetch(URL_TO_TELEGRAM, function(err) {
        if (err != null) {
          logLineUp(getI18nEntry("CONNECTING_TELEGRAM_FAILED"));
          notifyFailure(`${getI18nEntry("CONNECTING_TELEGRAM_FAILED")}\n${getI18nEntry("CONNECTING_FAILED")}:${err}\n${getI18nEntry('CONNECTING_RETRY')}`);
          return;
        }
        logLineUp(getI18nEntry("LAUNCH"));
        openupTeleme();
      });
    });
  };

  notifyFailure = function(msg) {
    analytics && analytics.event('client_desktop', 'conect_failed');
    if (confirm(msg)) {
      setTimeout(main, 888);
      EL_BTN_HELP.fadeIn('slow');
      analytics && analytics.event('client_desktop', 'connect_retry');
    } else {
      nw.App.quit();
    }
  };

  $(document).ready(function() {
    reinstateNodes(main);
    nw && nw.Window.get().on('new-win-policy', function(frame, url, policy) {
      //alert "DOWN url:#{url}"
      // do not open the window
      policy.ignore();
      // and open it in external browser
      nw.Shell.openExternal(url);
    });
  });

  try {
    analytics.initialize('UA-115166795-1');
  } catch (error) {
    err = error;
    console.log("fail analytics.initialize. err:", err);
  }

  analytics && analytics.pageview('/client/desktop');

  analytics && analytics.event('client_desktop', 'launch');

}).call(this);
