// Generated by CoffeeScript 2.3.2
(function() {
  var EL_LABELDOWN, EL_LABELUP, EL_TITLE, LANGUAGE_CODE, STATE, URL_TO_TELEGRAM, URL_TO_TELEME_WEB, doFetch, logLineUp, openupTeleme, reinstateNodes, step0;

  STATE = 0;

  EL_TITLE = null;

  EL_LABELUP = null;

  EL_LABELDOWN = null;

  LANGUAGE_CODE = "en";

  reinstateNodes = function() {
    EL_TITLE = $('#ELTitle');
    EL_LABELUP = $('#ELLabelUp');
    EL_LABELDOWN = $('#ELLabelDown');
    EL_LABELUP.text(navigator.userAgent);
  };

  URL_TO_TELEME_WEB = `https://www.teleme.io/web?utm_source=teleme_desktop&utm_medium=referral&hl=${LANGUAGE_CODE}&r=${Date.now()}`;

  URL_TO_TELEGRAM = `https://telegram.org/js/telegram-widget.js?r=${Date.now()}`;

  doFetch = function(url, callback) {
    fetch(URL_TO_TELEME_WEB).then(function(res) {
      if (!(res && res.status >= 200 && res.status < 400)) {
        throw new Error(`invalid http status ${res.status} from the server.`);
      }
      return res;
    }).then(function() {
      return callback();
    }).catch(function(err) {
      console.log(`ERROR _httpGetJson url ${url}. error:`, err);
      callback(err);
    });
  };

  openupTeleme = function() {
    var options;
    options = {
      "title": "TeleMe Desktop",
      "width": 1118,
      "height": 598,
      "min_width": 518,
      "min_height": 518
    };
    return nw.Window.open(URL_TO_TELEME_WEB, options, function(newWin) {
      nw.Window.close();
    });
  };

  logLineUp = function(msg) {
    return EL_LABELUP.text(String(msg || ''));
  };

  step0 = function() {
    reinstateNodes();
    logLineUp("connecting to the server...");
    doFetch(URL_TO_TELEME_WEB, function(err) {
      if (err != null) {
        alert(`Fail to connect to TeleMe server. \nPlease check your network connection. \nError:${err}`);
        return;
      }
      logLineUp("connecting to Telegram Web Service...");
      doFetch(URL_TO_TELEGRAM, function(err) {
        if (err != null) {
          alert(`Fail to connect to Telegram Web Service. \nPlease check your network connection. \nError:${err}`);
          return;
        }
        logLineUp("Staring up.");
        openupTeleme();
      });
    });
  };

  $(document).ready(step0);

}).call(this);
